#!/usr/bin/env bash
#End the script immediately if any command or pipe exits with a non-zero status.
set -eo pipefail

recyclebin="$HOME/recyclebin"
restorefile="$HOME/.restore.info"

# the basic restore function
# Uses the sed command to remove lines
restore() {
      for each_match in $path_matches
          do
              file_name_inode=$( echo $each_match | sed 's/:.*//')
              file_restore_path=$( echo $each_match | sed 's/.*://')

              
              if [ -f $file_restore_path ]; then 

                read -p "Do you want to overwrite $fileName? (y/n)" yn
                case $yn in
                    [Yy]* ) continue;;
                    [Nn]* ) exit 1;;
                    * ) echo "Please answer yes or no."; exit 1;;
                esac
              fi
              
              dir_path=$(echo ${file_restore_path%/*})

              # Check if the current directory exists, if not create it
              if [ ! -d $dir_path ]; then
                mkdir $dir_path
              fi

              # Proceed to move files and delete .restore.info using sed command
              mv $recyclebin/$file_name_inode $file_restore_path
              sed -i "\'$each_match'd" $restorefile

              echo "The file $fileName has been restored"

          done
}

# This checks if a filename is provided, and if the file exists inside the recyclebin
if [ ! -z $1 ]; then
   fileName=$1
   if [ -f $recyclebin/$fileName ]; then

   echo "File exists, do stuff"

    # TO double check, an be removed
    #if [ ! $(grep -q "$fileName" $restorefile) ]; then
        
        #Internal Field Separator 
        IFS=$'\n'
        path_matches=$(grep -h "$fileName" $restorefile)
        restore    
    #fi
    else
    echo " The File: $fileName dose not exist"

    fi 

else
    echo "No filename provided"
    
    exit 1
fi

